modLoader="javafml" #mandatory
loaderVersion="[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="ambientadditions" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Ambient Additions" #mandatory
credits="LukeGrahamLandry, OmayPaty, Graustreif2004, Ninni, MightyGoat42, PoopHead27" #optional
authors="codyhuh, VakyPanda"
description='''Adds more ambient wildlife to your world!'''

[[dependencies.ambientadditions]]
modId="forge"
mandatory=true
versionRange="[43,)"
ordering="NONE"
side="BOTH"

[[dependencies.ambientadditions]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"

#[[dependencies.ambientadditions]]
#modId="geckolib"
#mandatory=true
## This version range declares a minimum of the current minecraft version up to but not including the next major version
#versionRange="[3.1,4.0)"
#ordering="NONE"
#side="BOTH"